-- DML data manipulation language

INSERT INTO ENDERECOS 
	(CEP, LOGRADOURO, BAIRRO, CIDADE, UF) 
	VALUES
    ("12345-123", "AV PAULISTA", "CENTRO", "SAO PAULO", "SP");

-- ALTER TABLE ENDERECOS CHANGE CIDADAE CIDADE VARCHAR(30);
-- ALTER TABLE ENDERECOS RENAME COLUMN CIDADAE TO CIDADE;

INSERT INTO CLIENTES VALUES (45567845906, "XPTO", "xpto@itau.com.br", "787", "", "12345-123"); 

DESC NOTASFISCAIS;

INSERT INTO COLABORADORES VALUES (0, "BILL GATES", "VENDEDOR", 4500);	

INSERT INTO NOTASFISCAIS VALUES (1, str_to_date("16/07/2020", "%d/%m/%Y"), "6503", 1000, 45567845906, 0);

select * from TELEFONES;

-- DELETE FROM TELEFONES WHERE (NUMERO = 1);

INSERT INTO TELEFONES VALUES (0, "11 97780-9343", 45567845906, "TIM");
INSERT INTO TELEFONES VALUES (0, "13 99773-5688", 45567845906, "CLARO");
INSERT INTO TELEFONES VALUES (2, "13 99773-5688", 45567845906, "CLARO");

DELETE FROM TELEFONES WHERE (ID = 2);

SELECT * FROM TELEFONES WHERE OPERADORA = "TIM"; 

SELECT * FROM TELEFONES WHERE OPERADORA LIKE "T%";
SELECT * FROM TELEFONES WHERE OPERADORA LIKE "%I%";
SELECT * FROM TELEFONES WHERE OPERADORA LIKE "%RO";
SELECT * FROM TELEFONES WHERE OPERADORA LIKE "%O";


INSERT INTO ENDERECOS 
	(CEP, LOGRADOURO, BAIRRO, CIDADE, UF) 
	VALUES
    ("11111-005", "AV DOS AUTONOMISTAS", "CENTRO", "SAO PAULO", "SP");
    
INSERT INTO ENDERECOS 
	(CEP, LOGRADOURO, BAIRRO, CIDADE, UF) 
	VALUES
    ("99242-993", "AV JK", "JK", "MARAGOGI", "AL");
    
INSERT INTO ENDERECOS 
	(CEP, LOGRADOURO, BAIRRO, CIDADE, UF) 
	VALUES
    ("03434-323", "AV BRASIL", "BAIRRO DOS PIMENTAS", "GUARULHOS", "SP");
    
SELECT * FROM ENDERECOS;
SELECT * FROM ENDERECOS ORDER BY CIDADE;
SELECT * FROM ENDERECOS WHERE CIDADE LIKE "%g%" ORDER BY BAIRRO;
SELECT COUNT(CIDADE) FROM ENDERECOS WHERE CIDADE="SAO PAULO";

SELECT * FROM CLIENTES;
SELECT * FROM NOTASFISCAIS;

SELECT * FROM CLIENTES AS C INNER JOIN ENDERECOS AS E ON C.CEP_ENDERECO=E.CEP;
SELECT C.NOME, C.CPF, E.BAIRRO FROM CLIENTES AS C INNER JOIN ENDERECOS AS E ON C.CEP_ENDERECO=E.CEP;

SELECT T.TELEFONE, C.NOME FROM TELEFONES AS T INNER JOIN CLIENTES AS C ON C.CPF=T.CPF_CLIENTE;

select * from TELEFONES;
DELETE FROM TELEFONES WHERE TELEFONE="13 99773-5688";	

SELECT * FROM COLABORADORES;
UPDATE COLABORADORES SET SALARIO = SALARIO*1.1, CARGO = "COORDENADOR" WHERE ID=0;
