create database notafiscal;

use notafiscal;

create table ENDERECOS(
	CEP VARCHAR(9) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PRIMARY KEY (CEP)
);

CREATE TABLE CLIENTES(
	CPF NUMERIC(11) NOT NULL,
    NOME VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(10),
    NUMERO_RESIDENCIAL VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(30),
    CEP_ENDERECO VARCHAR(9) NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CEP_ENDERECO) REFERENCES ENDERECOS(CEP)
);

DROP TABLE TELEFONES;

CREATE TABLE TELEFONES(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TELEFONE VARCHAR(14) NOT NULL,
    CPF_CLIENTE NUMERIC(11) NOT NULL,
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF)
);

ALTER TABLE TELEFONES ADD OPERADORA VARCHAR(15) NOT NULL;

