-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE NOTASFISCAIS (
NUMERO NUMERIC(10) PRIMARY KEY NOT NULL,
DATAEMISSAO DATE NOT NULL,
CFOP VARCHAR(10) NOT NULL,
TOTAL NUMERIC(10,2) NOT NULL,
CPF_CLIENTE NUMERIC(11),
ID_COLABORADOR NUMERIC(10) NOT NULL,
FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADORES(ID)
);

CREATE TABLE COLABORADORES (
ID NUMERIC(10) PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
SALARIO NUMERIC(10,2) NOT NULL
);

CREATE TABLE ITENSNF (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
QTDE VARCHAR(10) NOT NULL,
VALORUNITARIO VARCHAR(10.2) NOT NULL,
NUMERO_NOTAFISCAL NUMERIC(10) NOT NULL,
ID_PRODUTO INT(10) NOT NULL,
FOREIGN KEY(NUMERO_NOTAFISCAL) REFERENCES NOTASFISCAIS (NUMERO),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS (ID)
);

CREATE TABLE PRODUTOS (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL,
VALORVENDA VARCHAR(10.2) NOT NULL,
VALORCOMPRA VARCHAR(10.2) NOT NULL,
QTDE VARCHAR(10) NOT NULL
);

CREATE TABLE CLIENTES (
CPF NUMERIC(11) PRIMARY KEY,
NOME VARCHAR(10),
EMAIL VARCHAR(10),
NUMERO_RESIDENCIAL VARCHAR(10),
COMPLEMENTO VARCHAR(30),
CEP_ENDERECO VARCHAR(9)
);

CREATE TABLE TELEFONES (
ID NUMERIC(10) PRIMARY KEY,
TELEFONE VARCHAR(14),
CPF_CLIENTE NUMERIC(11),
FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTES (CPF)
);

CREATE TABLE ENDERECOS (
CEP VARCHAR(9) PRIMARY KEY,
LOGRADOURO VARCHAR(50),
BAIRRO VARCHAR(30),
CIDADE VARCHAR(30),
UF VARCHAR(2)
);

ALTER TABLE NOTASFISCAIS ADD FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTES (CPF);
ALTER TABLE NOTASFISCAIS ADD FOREIGN KEY(ID_COLABORADOR) REFERENCES COLABORADORES (ID);
ALTER TABLE ITENSNF ADD FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS (ID);
ALTER TABLE CLIENTES ADD FOREIGN KEY(CEP_ENDERECO) REFERENCES ENDERECOS (CEP);
